### ISSUE TITLE
wish: ghc-syntax-highlighter in ghci

### ISSUE THREAD

**Issue by v217** [mrkkrp/ghc-syntax-highlighter#12]
This would be great!
I have no idea how difficult it would be to implement this?  
The **BIG ADVANTAGE** would be that things like [shh](http://hackage.haskell.org/package/shh) would work with no modifications. Are there editors which support `ghc-syntax-highlighter`?

**Comment by v217** [comment]
I found out about [ghci-pretty](http://hackage.haskell.org/package/ghci-pretty).

**Comment by mrkkrp** [comment]
This would be a feature request for GHC, not for `ghc-syntax-highlighter`. GHC is in a good position to use its own tokenizer to highlight the code it outputs (and it cannot really depend on `ghc-syntax-highlighter` anyway because it's not a boot library).

I do not know how difficult would it be to implement it though.
