### ISSUE TITLE
conflicting bounds on 0.6.0.0

### ISSUE THREAD

**Issue by simonmichael** [mrkkrp/ghc-syntax-highlighter#17]
Hi, the 0.0.6.0 release says base >=4.12 (suggesting GHC 8.6+) but also ghc-lib-parser ==8.10.* (GHC 8.10 only). I think this is causing confusion somehow, perhaps because base is special, for stackage CI ([failure](https://travis-ci.org/github/commercialhaskell/stackage/builds/674651965), [discussion](https://github.com/commercialhaskell/stackage/pull/5304)) and perhaps others ? A possible fix: add a revision to 0.6.0.0 limiting to base == 4.14* (GHC 8.10 only).

**Comment by mrkkrp** [comment]
`ghc-lib-parser` is not 8.10 only. It provides GHC code as a library (in this case, code corressponds to 8.10) but compiles with several GHC versions. See [here](https://hackage.haskell.org/package/ghc-lib-parser) we can use `base >= 4.11 && < 4.15` with it. It [succeeds](https://travis-ci.org/github/mrkkrp/ghc-syntax-highlighter) on my CI.

Looking at the failure it seems that Stackage uses `ghc-lib-parser-8.8.3.20200412.1` and this is not what the latest release of `ghc-syntax-highighter` wants. You can put a bound on versions of `ghc-syntax-highter` for now. I released a new version because of this ticket https://github.com/commercialhaskell/stackage/issues/5257.

**Comment by simonmichael** [comment]
I guess I misunderstood ghc-syntax-highlighter's ghc-lib-parser ==8.10.* bound - this does not mean GHC 8.10 only. I'm still confused but that doesn't matter, I think the action you're suggesting is to add a ghc-syntax-highlighter <0.6.0.0 bound in stackage for now ? Will do, unless you say otherwise.

**Comment by mrkkrp** [comment]
Yes, the bound should be removed when https://github.com/commercialhaskell/stackage/issues/5257 is closed.

**Comment by simonmichael** [comment]
Seems to have been just an issue with stackage's CI, please feel free to close this. (And thanks.)
